#!/usr/bin/env python

import numpy as np

import pxul
from mdprep import editconf
import prody

import os

def getopts():
    from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter

    p = ArgumentParser()
    p.add_argument('-i', '--input', required=True, help='A gromacs file (pdb,tpr,gro)')
    p.add_argument('-s', '--select', required=True, help='atom selection string')
    p.add_argument('-o', '--output', required=True)

    opts = p.parse_args()
    opts.input = os.path.abspath(opts.input)

    return opts    


def main(opts):
    
    with pxul.os.TmpDir():
        editconf(f=opts.input, o='topol.pdb')
        prot = prody.parsePDB('topol.pdb')
        ix = prot.select(opts.select).getIndices()

    np.savetxt(opts.output, ix, fmt='%d')


if __name__ == '__main__':
    main(getopts())
